DATA    SEGMENT
DATA    ENDS
STACK   SEGMENT PARA STACK'STACK'
        DB 50 DUP(?)
STACK   ENDS
CODE    SEGMENT
        ASSUME  CS:CODE,DS:DATA,SS:STACK
START:  MOV AX,DATA
        MOV DS,AX
	SBB AX,AX
	MOV AL,4AH
	MOV BL,AL
        MOV DL,AL
        MOV CL,4
        SHR DL,CL
        CMP DL,9
        JBE NEXT1
        ADD DL,7
NEXT1:	ADD DL,30H
	MOV AH,2
	INT 21H	
	MOV DL,BL
	AND DL,0FH
	CMP DL,9
	JBE NEXT2
	ADD DL,7
NEXT2:	ADD DL,30H
	MOV AH,2
	INT 21H
        MOV DL,48H
        INT 21H
        MOV AH,4CH
        INT 21H
CODE    ENDS
        END START
